AllCops:
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - 'spec/**'
    - 'lib/**'
  Exclude:
    - 'spec/vagrantfiles/**/*'

Metrics/MethodLength:
  Max: 15
