AllCops:
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - 'spec/**'
    - 'lib/**'
  Exclude:
    - 'script_parts/**'
    - 'avsh_config_example.rb'

Metrics/MethodLength:
  Max: 20
